version: '3'

services:
  database:
    image: mongo

  apiserver:
    image: paulushc/k8s-bootcamp-api
    environment:
      - MONGO=database
    depends_on:
      - database
    ports:
      - "3000"
    links:
      - database

  webserver:
    image: paulushc/k8s-bootcamp-web
    depends_on:
      - apiserver
    ports:
      - "5000:80"
    links:
      - apiserver