apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-conf
  labels:
    name: grafana-server-conf
  namespace: monitoring
data:
  config.monitoring: |-
    GF_SECURITY_ADMIN_PASSWORD=foobar
    GF_USERS_ALLOW_SIGN_UP=false
  datasource.yml: |-
      apiVersion: 1
      deleteDatasources:
        - name: Prometheus
          orgId: 1
      datasources:
        - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-service:9090
        password:
        user:
        database:
        basicAuth: true
        basicAuthUser: admin
        basicAuthPassword: foobar
        withCredentials:
        isDefault:
        jsonData:
          graphiteVersion: "1.1"
          tlsAuth: false
          tlsAuthWithCACert: false
        secureJsonData:
          tlsCACert: "..."
          tlsClientCert: "..."
          tlsClientKey: "..."
        version: 1
        editable: true

